spring.application.name=SistemaCitas

spring.datasource.url=jdbc:postgresql://localhost:5432/proyecto_citas_db
spring.datasource.username=postgres
spring.datasource.password=Pacheco22!

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true